# Generated by Django 3.1.7 on 2021-04-04 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0005_auto_20210404_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingmark',
            name='department',
        ),
        migrations.RemoveField(
            model_name='missingmark',
            name='name',
        ),
        migrations.RemoveField(
            model_name='missingmark',
            name='programme',
        ),
        migrations.RemoveField(
            model_name='missingmark',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='missingmark',
            name='user',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=200, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.department')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.programme')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='missingmark',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.student'),
        ),
    ]
