# Generated by Django 3.1.7 on 2021-04-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20210404_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missingmark',
            options={'verbose_name_plural': 'Missing Marks'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'All Students'},
        ),
    ]
